{% set name = "rply" %}
{% set version = "0.7.7" %}
{% set sha256 = "4d6d25703efd28fb3d5707f7b3bd4fe66c306159a5c25af10ba26d206a66d00d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - appdirs

  run:
    - python >={{ python_min }}
    - appdirs

test:
  requires:
    - python {{ python_min }}
  imports:
    - rply

about:
  home: https://github.com/alex/rply
  license: BSD
  license_file: LICENSE
  summary: 'A pure Python Lex/Yacc that works with RPython'
  description: |
    Welcome to RPLY! A pure python parser generator, that
    also works with RPython. It is a more-or-less direct port
    of David Beazley’s awesome PLY, with a new public API, and RPython support.
  doc_url: https://rply.readthedocs.io/en/latest/
  dev_url: https://github.com/alex/rply

extra:
  recipe-maintainers:
    - drewokane
