travis:
  secure:
    BINSTAR_TOKEN: gTom5m2dAW7LbHKORqAYiIRnOTezjLGJGfljsdyGVCjAZ94qhirSgYsLRg+juUyyZa1l453hO0t6GRxkyGrMiWhxNr8UY5gXB+SrQJiUGeVJTV6OY2+4xVTDH4SeyX3B95Qlbwg5X7bgqG5bah94UYuZIf73jDRitfDtLlNhqprFvhy54ZAiSmbPpBeEfy07m8BcZG0fFtJJnfDzDwDRXJztB8jT5dA2mpgNdnx17DuU6Kua2FumOPWcu7NzuWKlx+cmJR+b2Qh4AVYdiPJxpKkiAFUNmVVkTQIIFXs1DYXMQ2PgPP61SW4MHDiNw6DBbOdob3j4XknhB6S4GJNBmhtrxb+2SCCeKku2YcFha6mAZs4RGMWdp2EEjPLY97QQfqGEVxyxdLjlORBzhDqsKXPtqSrBmE5DSZWA+yh6RDztua7/6EKzHyOL8ZMaUBJo7h99CrpGLV8i+AbaQbaBM4GRbANtk6bEquN3nBxEEtiwi5LC3JJ8bAtWjg8fZjfGDBmlpZ0dFaHcbD0RxW1+xCN3AB8wuQJHE05AHNcKMXbjK3KiSmnw6ZsRxxNTWoo08b0Dn1pJuoQOummd8OeWzqi1xexcNjFBotMfyARxIHRLBibjYrZFoaQ8hAptJ7hsXZQQVK9XDD7JhOk1oYSxvL8vXc5SLQ7aav+8z+2Rqh8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
