travis:
  secure:
    BINSTAR_TOKEN: SrO2FU5QMSWnaHbIoTy32es92qYlMECYvqvqyhbPlszwgrZqVO+FX3D1/XiGRV/kc8IRNbGIwHoKYkS5+sVRarK2o+n2ph5YqYMFsV+6QPtG1PyHDJ1kHfYdwhXzBe+3/HPd5AppHv14Kir1o6NrwbHhsrKGFpWnD9Ik0V+pZMMpUNmwZrbLOi+aBLq7xlu5Tt7wLXEGYfAIA1+fNfZOqJh1rjCqobGR+dNTM8ElsP7N9DJr3ENmsQ2USPOADQF0AEBXH/P7y58wIQXyryKOACnJQF8VGRvJ2cJBtMYPyo07lm2+Z9GfAK9LIkjTFKAif8zN1fmrMu9CB68ajn9Ye/v3P7XFZIPpl2Tf2dYFT62tbkSJusHwvlSZeWKhuNRrGbyaY6MEnfNT4k0LbqHq5rmGZCuytI9XA4lU/uG2BOumSaNnjKv/zTvpQmj5RlWOuz8wg8HHRjPz/703HmG0f1RmC4ri4rJfHkDzTJgXQyOsv21mk5CpBmXdtI3JgoBjQ/bvY/yi2iewW3CILOSBlB/R2u+R6JVoOfgIkiTCBOGBByXChUX0Cs1LnyhjY+BetuEJLd5uDW2Ohq9Jj4orfKnxldQOrnKRFlUKC9N0TEEA4Hv8yC3OkuhkdKhf9QxU4YNjMxs8tAgqRNzwb7cqlWEGBo7oSNpky4jHV6pGr3M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
